server:
  port: 8080

spring:
  application:
    name: nursing-center-system
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  # Jackson 日期时间格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nursing_center?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: 
    - classpath*:mapper/*.xml
    - classpath*:com/nursing/center/mapper/*.xml

# JWT 配置
jwt:
  secret: nursing-center-secret-key-2023
  expiration: 86400000 # 24小时

# Swagger 配置
springfox:
  documentation:
    swagger-ui:
      enabled: true

# 日志配置
logging:
  file:
    name: logs/app.log
